"""empty message

Revision ID: 1fc4cf756b2b
Revises: 4fd66654aec1
Create Date: 2020-04-25 22:35:16.037749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fc4cf756b2b'
down_revision = '4fd66654aec1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('activation_code', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'activation_code')
    # ### end Alembic commands ###
