"""empty message

Revision ID: 4fd66654aec1
Revises: 90764a66cb6d
Create Date: 2020-04-25 18:32:44.078935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fd66654aec1'
down_revision = '90764a66cb6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('client', 'phone_number',
               existing_type=sa.VARCHAR(length=12),
               type_=sa.String(length=14),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('client', 'phone_number',
               existing_type=sa.String(length=14),
               type_=sa.VARCHAR(length=12),
               existing_nullable=False)
    # ### end Alembic commands ###
