"""empty message

Revision ID: 5bfc7927745f
Revises: d662c5180922
Create Date: 2020-04-28 13:31:57.886712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bfc7927745f'
down_revision = 'd662c5180922'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('booking', 'status',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('booking', 'status',
               existing_type=sa.String(),
               type_=sa.BOOLEAN(),
               nullable=True, postgresql_using='status::boolean')
    # ### end Alembic commands ###
