"""empty message

Revision ID: 90764a66cb6d
Revises: 
Create Date: 2020-04-25 17:54:30.383009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90764a66cb6d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by NAlembic - please adjust! ###
    op.add_column('client', sa.Column('active', sa.Boolean(), nullable=False, server_default='False'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'active')
    # ### end Alembic commands ###
