"""empty message

Revision ID: 9603bfa0d63a
Revises: 5bfc7927745f
Create Date: 2020-05-05 21:48:13.657508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9603bfa0d63a'
down_revision = '5bfc7927745f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('sound_engineer_id', sa.Integer(), nullable=False, server_default='1'))
    op.drop_constraint('booking_studio_id_start_time_key', 'booking', type_='unique')
    op.create_unique_constraint(None, 'booking', ['studio_id', 'start_time', 'sound_engineer_id'])
    op.create_foreign_key(None, 'booking', 'sound_engineer', ['sound_engineer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'booking', type_='foreignkey')
    op.drop_constraint(None, 'booking', type_='unique')
    op.create_unique_constraint('booking_studio_id_start_time_key', 'booking', ['studio_id', 'start_time'])
    op.drop_column('booking', 'sound_engineer_id')
    # ### end Alembic commands ###
